
# Author: Claire Gregg

version: '2'
services:

    employee1:
        build:
            dockerfile:
                client/Dockerfile
        # Appends the application id and gateway
        command: ["AABBCCDDEEFF", "192.168.17.254"]
        networks:
            home1:
                ipv4_address: 192.168.17.17
        depends_on:
            - controller
            - gateway_e1_to_isp
            - gateway_e2_to_isp
            - gateway_e3_to_isp
            - gateway_isp_to_int
            - gateway_int_to_cloud
            - cloud_server_1
            - cloud_server_2

    employee2:
        build:
            dockerfile:
                client/Dockerfile
        # Appends the application id and gateway
        command: ["AABBCCEEEEFF", "192.168.18.254"]
        networks:
            home2:
                ipv4_address: 192.168.18.19
        depends_on:
            - controller
            - gateway_e1_to_isp
            - gateway_e2_to_isp
            - gateway_e3_to_isp
            - gateway_isp_to_int
            - gateway_int_to_cloud
            - cloud_server_1
            - cloud_server_2

    employee3:
        build:
            dockerfile:
                client/Dockerfile
        # Appends the application id and gateway
        command: ["AABBCCDDEEFA", "192.168.19.10"]
        networks:
            home3:
                ipv4_address: 192.168.19.21
        depends_on:
            - controller
            - gateway_e1_to_isp
            - gateway_e2_to_isp
            - gateway_e3_to_isp
            - gateway_isp_to_int
            - gateway_int_to_cloud
            - cloud_server_1
            - cloud_server_2

    interactive_employee_4:
        build:
            dockerfile:
                interactive_client/Dockerfile
        # Appends the application id and gateway
        command: ["AABBBBBBBBBB", "192.168.19.10"]
        networks:
            home3:
                ipv4_address: 192.168.19.24
        depends_on:
            - controller
            - gateway_e1_to_isp
            - gateway_e2_to_isp
            - gateway_e3_to_isp
            - gateway_isp_to_int
            - gateway_int_to_cloud
            - cloud_server_1
            - cloud_server_2
        stdin_open: true
        tty: true
        
    cloud_server_1:
        build:
            dockerfile:
                server/Dockerfile
        # Appends the application id and gateway
        command: ["FFEEDDCCBBAA", "172.20.7.9"]
        networks:
            cloud:
                ipv4_address: 172.20.16.8
        depends_on:
            - controller
            - gateway_e1_to_isp
            - gateway_e2_to_isp
            - gateway_e3_to_isp
            - gateway_isp_to_int
            - gateway_int_to_cloud

    cloud_server_2:
        build:
            dockerfile:
                server/Dockerfile
        # Appends the application id and gateway
        command: ["FFFFFFFFFFFF", "172.20.7.9"]
        networks:
            cloud:
                ipv4_address: 172.20.10.11
        depends_on:
            - controller
            - gateway_e1_to_isp
            - gateway_e2_to_isp
            - gateway_e3_to_isp
            - gateway_isp_to_int
            - gateway_int_to_cloud

    gateway_e1_to_isp:
        build:
            dockerfile:
                forwarders/Dockerfile
        # Appends any IP addresses this element can access
        command: ["192.168.17.17","172.30.6.255","172.30.2.6","172.30.2.7"]
        networks:
            home1:
                ipv4_address: 192.168.17.254
            isp:
                ipv4_address: 172.30.8.45
        depends_on:
            - tcpdump
            - controller
    

    gateway_e2_to_isp:
        build:
            dockerfile:
                forwarders/Dockerfile
        # Appends any IP addresses this element can access
        command: ["192.168.18.19","172.30.6.255","172.30.8.45","172.30.2.7"]
        networks:
            home2:
                ipv4_address: 192.168.18.254
            isp:
                ipv4_address: 172.30.2.6
        depends_on:
            - tcpdump
            - controller
    

    gateway_e3_to_isp:
        build:
            dockerfile:
                forwarders/Dockerfile
        # Appends any IP addresses this element can access
        command: ["192.168.19.21","172.30.6.255","172.30.8.45","172.30.2.6","192.168.19.21"]
        networks:
            home3:
                ipv4_address: 192.168.19.10
            isp:
                ipv4_address: 172.30.2.7
        depends_on:
            - tcpdump
            - controller
    

    gateway_isp_to_int:
        build:
            dockerfile:
                forwarders/Dockerfile
        # Appends any IP addresses this element can access
        command: ["172.30.8.45","10.30.4.244","172.30.2.6","172.30.2.7"]
        networks:
            isp:
                ipv4_address: 172.30.6.255
            internet:
                ipv4_address: 10.30.5.8
        depends_on:
            - tcpdump
            - controller
    

    gateway_int_to_cloud:
        build:
            dockerfile:
                forwarders/Dockerfile
        # Appends any IP addresses this element can access
        command: ["10.30.5.8","172.20.16.8","172.20.7.11"]
        networks:
            internet:
                ipv4_address: 10.30.4.244
            cloud:
                ipv4_address: 172.20.7.9
        depends_on:
            - tcpdump
            - controller
    
    controller:
        build:
            dockerfile:
                controller/Dockerfile
        command: ["192.168.17.2","192.168.18.2","192.168.19.2","172.30.0.2","10.30.0.2","172.20.0.2"]
        networks:
            home1:
                ipv4_address: 192.168.17.2
            home2:
                ipv4_address: 192.168.18.2
            home3:
                ipv4_address: 192.168.19.2
            isp:
                ipv4_address: 172.30.0.2
            internet:
                ipv4_address: 10.30.0.2
            cloud:
                ipv4_address: 172.20.0.2
        depends_on:
            - tcpdump
    
    tcpdump:
        image: kaazing/tcpdump
        network_mode: "host"
        volumes:
            - ./tcpdump:/tcpdump
        command: ["-i", "any", "udp", "-w", "tcpdump/tcpdump.pcap"] 

networks:
    home1:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.17.0/24
    home2:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.18.0/24
    home3:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.19.0/24
    isp:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.30.0.0/16
    internet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.30.0.0/16
    cloud:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16