
# Author: Claire Gregg

version: '2'
services:

    employee:
        build:
            dockerfile:
                client/Dockerfile
        # Appends the application id and gateway
        command: ["AABBCCDDEEFF", "192.168.17.254"]
        networks:
            home:
                ipv4_address: 192.168.17.17
        depends_on:
            - controller
            - gateway_e_to_isp
            - gateway_isp_to_int
            - gateway_int_to_cloud
            - cloud_provider

    cloud_provider:
        build:
            dockerfile:
                server/Dockerfile
        # Appends the application id and gateway
        command: ["FFEEDDCCBBAA", "172.20.7.9"]
        networks:
            cloud:
                ipv4_address: 172.20.16.8
        depends_on:
            - controller
            - gateway_e_to_isp
            - gateway_isp_to_int
            - gateway_int_to_cloud

    gateway_e_to_isp:
        build:
            dockerfile:
                forwarders/Dockerfile
        # Appends any IP addresses this element can access
        command: ["192.168.17.17","172.30.6.255"]
        networks:
            home:
                ipv4_address: 192.168.17.254
            isp:
                ipv4_address: 172.30.8.45
        depends_on:
            - tcpdump
            - controller
    

    gateway_isp_to_int:
        build:
            dockerfile:
                forwarders/Dockerfile
        # Appends any IP addresses this element can access
        command: ["172.30.8.45","10.30.4.244"]
        networks:
            isp:
                ipv4_address: 172.30.6.255
            internet:
                ipv4_address: 10.30.5.8
        depends_on:
            - tcpdump
            - controller
    

    gateway_int_to_cloud:
        build:
            dockerfile:
                forwarders/Dockerfile
        # Appends any IP addresses this element can access
        command: ["10.30.5.8","172.20.16.8"]
        networks:
            internet:
                ipv4_address: 10.30.4.244
            cloud:
                ipv4_address: 172.20.7.9
        depends_on:
            - tcpdump
            - controller
    
    controller:
        build:
            dockerfile:
                controller/Dockerfile
        command: ["192.168.17.2","172.30.0.2","10.30.0.2","172.20.0.2"]
        networks:
            home:
                ipv4_address: 192.168.17.2
            isp:
                ipv4_address: 172.30.0.2
            internet:
                ipv4_address: 10.30.0.2
            cloud:
                ipv4_address: 172.20.0.2
        depends_on:
            - tcpdump
    
    tcpdump:
        image: kaazing/tcpdump
        network_mode: "host"
        volumes:
            - ./tcpdump:/tcpdump
        command: ["-i", "any", "udp", "-w", "tcpdump/tcpdump.pcap"] 

networks:
    home:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.17.0/24
    isp:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.30.0.0/16
    internet:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.30.0.0/16
    cloud:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16