
# Author: Claire Gregg

version: '2'
services:

    employee:
        build:
            dockerfile:
                client/Dockerfile
        # Appends the application id and gateway
        command: ["AABBCCDDEEFF", "192.168.17.254"]
        networks:
            home:
                ipv4_address: 192.168.17.17
        depends_on:
            - controller
            - gateway
            - cloud_provider

    cloud_provider:
        build:
            dockerfile:
                server/Dockerfile
        # Appends the application id and gateway
        command: ["FFEEDDCCBBAA", "172.30.2.5"]
        networks:
            cloud:
                ipv4_address: 172.30.16.8
        depends_on:
            - controller
            - gateway

    gateway:
        build:
            dockerfile:
                forwarders/Dockerfile
        # Appends any IP addresses this element can access
        command: ["192.168.17.17","172.30.16.8"]
        networks:
            home:
                ipv4_address: 192.168.17.254
            cloud:
                ipv4_address: 172.30.2.5
        depends_on:
            - tcpdump
            - controller
    
    controller:
        build:
            dockerfile:
                controller/Dockerfile
        command: ["192.168.17.2","172.30.1.2"]
        networks:
            home:
                ipv4_address: 192.168.17.2
            cloud:
                ipv4_address: 172.30.1.2
        depends_on:
            - tcpdump
    
    tcpdump:
        image: kaazing/tcpdump
        network_mode: "host"
        volumes:
            - ./tcpdump:/tcpdump
        command: ["-i", "any", "udp", "-w", "tcpdump/tcpdump.pcap"] 

networks:
    home:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.17.0/24
    cloud:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.30.0.0/16